function run_checks
%RUN_CHECKS Independent phase, limiting-case, and input-contract checks.
speedOfLightMps = 299792458;
frequencyHz = 1e9;
velocityFactor = 0.66;
phaseVelocityMps = velocityFactor*speedOfLightMps;
wavelengthM = phaseVelocityMps/frequencyHz;
quarterWaveM = wavelengthM/4;
angleTolerance = 1e-10;
lengthTolerance = 1e-12;
phasorTolerance = 1e-12;

quarterWave = model(frequencyHz,quarterWaveM,velocityFactor);
assert(abs(quarterWave.phaseVelocityMps-197863022.28) < 1e-6, ...
    'Velocity factor 0.66 must give the expected phase velocity.');
assert(abs(quarterWave.wavelengthM-0.19786302228) < lengthTolerance, ...
    'The 1 GHz guided wavelength must be 0.19786302228 m.');
assert(abs(quarterWave.physicalLengthM-0.04946575557) < lengthTolerance, ...
    'The baseline path must be one guided quarter wavelength.');
assert(abs(quarterWave.propagationDelayS-250e-12) < 1e-21, ...
    'A guided quarter wavelength must delay 1 GHz by 250 ps.');
assert(abs(quarterWave.electricalCycles-0.25) < phasorTolerance, ...
    'A guided quarter wavelength must be 0.25 electrical cycles.');
assert(abs(quarterWave.electricalLengthRad-pi/2) < phasorTolerance, ...
    'A guided quarter wavelength must have beta*l = pi/2 radians.');
assert(abs(quarterWave.electricalLengthDeg-90) < angleTolerance, ...
    'A guided quarter wavelength must have positive electrical length 90 degrees.');
assert(abs(quarterWave.unwrappedTransferPhaseDeg+90) < angleTolerance, ...
    'The exp(+j*omega*t) convention must give -90 degrees of through phase.');
assert(abs(quarterWave.wrappedTransferPhaseDeg+90) < angleTolerance, ...
    'The quarter-wave phase must remain -90 degrees after wrapping.');
assert(abs(quarterWave.transferPhasor+1j) < phasorTolerance, ...
    'The ideal quarter-wave transfer phasor must be -j.');
assert(abs(quarterWave.transferMagnitude-1) < phasorTolerance, ...
    'The ideal matched lossless line must have unity transfer magnitude.');
assert(abs(quarterWave.phaseEquivalentLengthM-quarterWaveM) < lengthTolerance, ...
    'A sub-wavelength quarter-wave path must equal its principal equivalent length.');

identityCases = [ ...
    1e6 0.125 0.50; ...
    2.4e9 0.037 0.72; ...
    10e9 0.250 0.90; ...
    1e11 1.000 0.10];
for index = 1:size(identityCases,1)
    testFrequencyHz = identityCases(index,1);
    testLengthM = identityCases(index,2);
    testVelocityFactor = identityCases(index,3);
    point = model(testFrequencyHz,testLengthM,testVelocityFactor);
    independentVelocityMps = testVelocityFactor*speedOfLightMps;
    independentDelayS = testLengthM/independentVelocityMps;
    independentCycles = testFrequencyHz*independentDelayS;
    independentAngleRad = 2*pi*independentCycles;
    independentAngleDeg = 360*independentCycles;
    independentPhasor = cos(independentAngleRad)-1j*sin(independentAngleRad);
    assert(abs(point.propagationDelayS-independentDelayS) < ...
        max(1e-21,1e-12*independentDelayS), ...
        'Delay must independently equal l/(velocityFactor*c_0).');
    assert(abs(point.electricalLengthRad-independentAngleRad) < ...
        max(1e-12,1e-12*independentAngleRad), ...
        'Electrical length must independently equal 2*pi*f*l/v_p.');
    assert(abs(point.electricalLengthDeg-independentAngleDeg) < ...
        max(1e-10,1e-12*independentAngleDeg), ...
        'Electrical length in degrees must equal 360*f*tau.');
    assert(abs(point.transferPhasor-independentPhasor) < 1e-9, ...
        'The transfer phasor must independently equal cos(theta)-j*sin(theta).');
    assert(abs(point.transferMagnitude-1) < phasorTolerance, ...
        'Every ideal matched lossless case must retain unity magnitude.');
    assert(point.wrappedTransferPhaseDeg >= -180 && ...
        point.wrappedTransferPhaseDeg < 180, ...
        'Wrapped through phase must stay in the half-open interval [-180,180).');
    assert(abs(point.phaseSlopeDegPerHz+360*point.propagationDelayS) < 1e-18, ...
        'Unwrapped phase slope must equal -360 times propagation delay.');
end

zeroLength = model(frequencyHz,0,velocityFactor);
assert(zeroLength.propagationDelayS == 0,'Zero length must have zero propagation delay.');
assert(zeroLength.electricalLengthDeg == 0,'Zero length must have zero electrical length.');
assert(zeroLength.unwrappedTransferPhaseDeg == 0,'Zero length must have zero through phase.');
assert(zeroLength.wrappedTransferPhaseDeg == 0,'Zero length must wrap to zero phase.');
assert(zeroLength.transferPhasor == 1,'Zero length must have H = 1.');

halfWave = model(frequencyHz,wavelengthM/2,velocityFactor);
assert(abs(halfWave.electricalLengthDeg-180) < angleTolerance, ...
    'A half wavelength must have 180 degrees of electrical length.');
assert(abs(halfWave.unwrappedTransferPhaseDeg+180) < angleTolerance, ...
    'A half wavelength must have -180 degrees of unwrapped phase.');
assert(abs(halfWave.wrappedTransferPhaseDeg+180) < angleTolerance, ...
    'The [-180,180) convention must retain a half wave at -180 degrees.');
assert(abs(halfWave.transferPhasor+1) < phasorTolerance, ...
    'A half wavelength must have H = -1.');

branchOffsetCycles = 1e-6;
belowHalfWave = model(frequencyHz,(0.5-branchOffsetCycles)*wavelengthM,velocityFactor);
aboveHalfWave = model(frequencyHz,(0.5+branchOffsetCycles)*wavelengthM,velocityFactor);
assert(belowHalfWave.wrappedTransferPhaseDeg < -179.99, ...
    'Phase just below a half wavelength must approach -180 degrees from above.');
assert(aboveHalfWave.wrappedTransferPhaseDeg > 179.99, ...
    'Phase just above a half wavelength must wrap to just below +180 degrees.');
assert(aboveHalfWave.wrappedTransferPhaseDeg-belowHalfWave.wrappedTransferPhaseDeg > 359.98, ...
    'Crossing the half-wave branch cut must expose the wrapped-phase jump.');
assert(abs(aboveHalfWave.transferPhasor-belowHalfWave.transferPhasor) < 2e-5, ...
    'The physical phasor must remain continuous across the wrapped-phase branch cut.');

fullWave = model(frequencyHz,wavelengthM,velocityFactor);
assert(abs(fullWave.electricalLengthDeg-360) < angleTolerance, ...
    'One wavelength must have 360 degrees of electrical length.');
assert(abs(fullWave.unwrappedTransferPhaseDeg+360) < angleTolerance, ...
    'One wavelength must have -360 degrees of unwrapped phase.');
assert(abs(fullWave.wrappedTransferPhaseDeg) < angleTolerance, ...
    'One wavelength must wrap to zero phase.');
assert(abs(fullWave.transferPhasor-1) < phasorTolerance, ...
    'One wavelength must return the transfer phasor to +1.');
assert(abs(fullWave.phaseEquivalentLengthM) < lengthTolerance, ...
    'Wrapped phase alone must map one full wavelength to the zero-length equivalent.');

baseFraction = model(frequencyHz,0.37*wavelengthM,velocityFactor);
plusOneCycle = model(frequencyHz,1.37*wavelengthM,velocityFactor);
assert(abs(baseFraction.transferPhasor-plusOneCycle.transferPhasor) < phasorTolerance, ...
    'Adding one guided wavelength must preserve the transfer phasor.');
assert(abs(baseFraction.wrappedTransferPhaseDeg-plusOneCycle.wrappedTransferPhaseDeg) < angleTolerance, ...
    'Adding one guided wavelength must preserve wrapped phase.');
assert(abs((plusOneCycle.unwrappedTransferPhaseDeg-baseFraction.unwrappedTransferPhaseDeg)+360) < angleTolerance, ...
    'Adding one guided wavelength must subtract 360 degrees of unwrapped phase.');
assert(abs((plusOneCycle.propagationDelayS-baseFraction.propagationDelayS)-1/frequencyHz) < 1e-21, ...
    'Adding one guided wavelength must add one signal period of delay.');

halfFrequency = model(0.5e9,quarterWaveM,velocityFactor);
doubleFrequency = model(2e9,quarterWaveM,velocityFactor);
assert(abs(halfFrequency.electricalLengthDeg-45) < angleTolerance, ...
    'Halving frequency at fixed length must halve electrical length.');
assert(abs(doubleFrequency.electricalLengthDeg-180) < angleTolerance, ...
    'Doubling frequency at fixed length must double electrical length.');
assert(abs(halfFrequency.propagationDelayS-quarterWave.propagationDelayS) < 1e-21 && ...
    abs(doubleFrequency.propagationDelayS-quarterWave.propagationDelayS) < 1e-21, ...
    'Frequency changes must not change nondispersive propagation delay.');

slowerMedium = model(frequencyHz,quarterWaveM,0.33);
assert(abs(slowerMedium.propagationDelayS-2*quarterWave.propagationDelayS) < 1e-21, ...
    'Halving velocity factor at fixed frequency and length must double delay.');
assert(abs(slowerMedium.electricalLengthDeg-2*quarterWave.electricalLengthDeg) < angleTolerance, ...
    'Halving velocity factor at fixed frequency and length must double electrical length.');
assert(abs(quarterWave.unwrappedRoundTripPhaseDeg+180) < angleTolerance, ...
    'A reflected quarter-wave path must accumulate -180 degrees on its round trip.');
assert(abs(quarterWave.wrappedRoundTripPhaseDeg+180) < angleTolerance, ...
    'The quarter-wave round-trip phase must wrap to -180 degrees.');

shortPath = quarterWave;
longPath = model(frequencyHz,5*quarterWaveM,velocityFactor);
assert(abs(longPath.propagationDelayS-1.25e-9) < 1e-21, ...
    'The 5 lambda_g/4 path must delay the signal by 1.25 ns.');
assert(abs(longPath.unwrappedTransferPhaseDeg+450) < angleTolerance, ...
    'The 5 lambda_g/4 path must have -450 degrees of unwrapped phase.');
assert(abs(longPath.wrappedTransferPhaseDeg+90) < angleTolerance, ...
    'The 5 lambda_g/4 path must wrap to -90 degrees.');
assert(abs(longPath.transferPhasor-shortPath.transferPhasor) < phasorTolerance, ...
    'The aliased long and short paths must have the same single-frequency phasor.');
assert(abs(longPath.phaseEquivalentLengthM-quarterWaveM) < lengthTolerance, ...
    'Wrapped phase alone must alias 5 lambda_g/4 to lambda_g/4.');
assert(abs((longPath.physicalLengthM-longPath.phaseEquivalentLengthM)-wavelengthM) < lengthTolerance, ...
    'The deliberately broken inference must miss exactly one guided wavelength.');

frequencyOffsetHz = 1e6;
lowPoint = model(frequencyHz-frequencyOffsetHz,quarterWaveM,velocityFactor);
highPoint = model(frequencyHz+frequencyOffsetHz,quarterWaveM,velocityFactor);
finiteDifferenceSlope = (highPoint.unwrappedTransferPhaseDeg- ...
    lowPoint.unwrappedTransferPhaseDeg)/(2*frequencyOffsetHz);
assert(abs(finiteDifferenceSlope+360*quarterWave.propagationDelayS) < 1e-18, ...
    'A frequency-sweep finite difference must recover delay from phase slope.');

largeEnvelopeEdge = model(1e11,1e3,0.1);
assert(all(isfinite([largeEnvelopeEdge.phaseVelocityMps largeEnvelopeEdge.wavelengthM ...
    largeEnvelopeEdge.propagationDelayS largeEnvelopeEdge.electricalCycles ...
    largeEnvelopeEdge.electricalLengthRad largeEnvelopeEdge.electricalLengthDeg ...
    largeEnvelopeEdge.transferPhasor largeEnvelopeEdge.phaseEquivalentLengthM])), ...
    'Supported upper endpoints must keep every derived metric finite.');
assert(largeEnvelopeEdge.electricalCycles > 3e6, ...
    'The upper accepted-boundary case must exercise millions of bounded phase cycles.');
smallEnvelopeEdge = model(1e3,0,1);
assert(all(isfinite([smallEnvelopeEdge.phaseVelocityMps smallEnvelopeEdge.wavelengthM ...
    smallEnvelopeEdge.propagationDelayS smallEnvelopeEdge.electricalLengthDeg ...
    smallEnvelopeEdge.transferPhasor smallEnvelopeEdge.phaseEquivalentLengthM])), ...
    'Supported lower endpoints must keep every derived metric finite.');

mustThrow(@() model(0,quarterWaveM,velocityFactor),'zero frequency');
mustThrow(@() model(-1,quarterWaveM,velocityFactor),'negative frequency');
mustThrow(@() model(999,quarterWaveM,velocityFactor),'frequency below supported envelope');
mustThrow(@() model(1e12,quarterWaveM,velocityFactor),'frequency above supported envelope');
mustThrow(@() model(Inf,quarterWaveM,velocityFactor),'nonfinite frequency');
mustThrow(@() model(NaN,quarterWaveM,velocityFactor),'NaN frequency');
mustThrow(@() model([1e9 2e9],quarterWaveM,velocityFactor),'nonscalar frequency');
mustThrow(@() model(1e9+1j,quarterWaveM,velocityFactor),'complex frequency');
mustThrow(@() model(frequencyHz,-1,velocityFactor),'negative physical length');
mustThrow(@() model(frequencyHz,1001,velocityFactor),'length above supported envelope');
mustThrow(@() model(frequencyHz,Inf,velocityFactor),'nonfinite physical length');
mustThrow(@() model(frequencyHz,NaN,velocityFactor),'NaN physical length');
mustThrow(@() model(frequencyHz,[0.1 0.2],velocityFactor),'nonscalar physical length');
mustThrow(@() model(frequencyHz,0.1+1j,velocityFactor),'complex physical length');
mustThrow(@() model(frequencyHz,quarterWaveM,0),'zero velocity factor');
mustThrow(@() model(frequencyHz,quarterWaveM,-0.5),'negative velocity factor');
mustThrow(@() model(frequencyHz,quarterWaveM,0.09),'velocity factor below supported envelope');
mustThrow(@() model(frequencyHz,quarterWaveM,1.01),'velocity factor above unity');
mustThrow(@() model(frequencyHz,quarterWaveM,Inf),'nonfinite velocity factor');
mustThrow(@() model(frequencyHz,quarterWaveM,NaN),'NaN velocity factor');
mustThrow(@() model(frequencyHz,quarterWaveM,[0.66 0.8]),'nonscalar velocity factor');
mustThrow(@() model(frequencyHz,quarterWaveM,0.66+1j),'complex velocity factor');

disp('P04 checks passed.');
end

function mustThrow(action,label)
didThrow = false;
try
    action();
catch
    didThrow = true;
end
assert(didThrow,'%s must be rejected.',label);
end
