function out = model(sourceVoltageRms, sourceResistanceOhm, sourceReactanceOhm, loadResistanceOhm, loadReactanceOhm)
%MODEL Calculate power transfer from a Thevenin source into a complex load.
%   All voltages and currents are RMS phasors. The passive source has
%   Z_s = R_s + jX_s and the load has Z_L = R_L + jX_L. The power-transfer
%   ratio is relative to the source's maximum available power. The broad
%   scalar input envelope prevents derived IEEE-754 overflow while covering
%   loads far outside the interactive range.
arguments
    sourceVoltageRms (1,1) double {mustBeReal,mustBeFinite,mustBeGreaterThanOrEqual(sourceVoltageRms,1e-12),mustBeLessThanOrEqual(sourceVoltageRms,1e6)} = 1
    sourceResistanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBePositive,mustBeGreaterThanOrEqual(sourceResistanceOhm,1e-9),mustBeLessThanOrEqual(sourceResistanceOhm,1e12)} = 50
    sourceReactanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBeGreaterThanOrEqual(sourceReactanceOhm,-1e12),mustBeLessThanOrEqual(sourceReactanceOhm,1e12)} = 50
    loadResistanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative,mustBeLessThanOrEqual(loadResistanceOhm,1e12)} = 50
    loadReactanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBeGreaterThanOrEqual(loadReactanceOhm,-1e12),mustBeLessThanOrEqual(loadReactanceOhm,1e12)} = -50
end

sourceImpedanceOhm = sourceResistanceOhm + 1j*sourceReactanceOhm;
loadImpedanceOhm = loadResistanceOhm + 1j*loadReactanceOhm;
conjugateMatchOhm = conj(sourceImpedanceOhm);
totalImpedanceOhm = sourceImpedanceOhm + loadImpedanceOhm;

currentA = sourceVoltageRms/totalImpedanceOhm;
currentRmsA = abs(currentA);
loadVoltagePhasorRms = currentA*loadImpedanceOhm;
loadVoltageRms = abs(loadVoltagePhasorRms);

loadPowerW = currentRmsA^2*loadResistanceOhm;
loadReactivePowerVar = currentRmsA^2*loadReactanceOhm;
sourceLossW = currentRmsA^2*sourceResistanceOhm;
availablePowerW = sourceVoltageRms^2/(4*sourceResistanceOhm);

powerTransferRatio = 4*sourceResistanceOhm*loadResistanceOhm/abs(totalImpedanceOhm)^2;
powerWaveGamma = (loadImpedanceOhm-conj(sourceImpedanceOhm))/totalImpedanceOhm;
powerTransferDb = 10*log10(powerTransferRatio);
mismatchLossDb = -powerTransferDb;
powerWaveReturnLossDb = -20*log10(abs(powerWaveGamma));
loadPowerDbm = 10*log10(loadPowerW/1e-3);

netReactanceOhm = sourceReactanceOhm + loadReactanceOhm;
currentPhaseDeg = 180/pi*angle(currentA);
loadShareOfDissipatedPower = loadResistanceOhm/(sourceResistanceOhm+loadResistanceOhm);

out = struct( ...
    'sourceVoltageRms',sourceVoltageRms, ...
    'sourceResistanceOhm',sourceResistanceOhm, ...
    'sourceReactanceOhm',sourceReactanceOhm, ...
    'loadResistanceOhm',loadResistanceOhm, ...
    'loadReactanceOhm',loadReactanceOhm, ...
    'sourceImpedanceOhm',sourceImpedanceOhm, ...
    'loadImpedanceOhm',loadImpedanceOhm, ...
    'conjugateMatchOhm',conjugateMatchOhm, ...
    'totalImpedanceOhm',totalImpedanceOhm, ...
    'currentA',currentA, ...
    'currentRmsA',currentRmsA, ...
    'currentPhaseDeg',currentPhaseDeg, ...
    'loadVoltagePhasorRms',loadVoltagePhasorRms, ...
    'loadVoltageRms',loadVoltageRms, ...
    'loadPowerW',loadPowerW, ...
    'loadReactivePowerVar',loadReactivePowerVar, ...
    'sourceLossW',sourceLossW, ...
    'availablePowerW',availablePowerW, ...
    'powerTransferRatio',powerTransferRatio, ...
    'powerWaveGamma',powerWaveGamma, ...
    'powerTransferDb',powerTransferDb, ...
    'mismatchLossDb',mismatchLossDb, ...
    'powerWaveReturnLossDb',powerWaveReturnLossDb, ...
    'loadPowerDbm',loadPowerDbm, ...
    'netReactanceOhm',netReactanceOhm, ...
    'loadShareOfDissipatedPower',loadShareOfDissipatedPower);
end
