function out = model(powerW, voltageRms, resistanceOhm, referencePowerW, referenceVoltageRms, referenceResistanceOhm)
%MODEL Convert power and RMS-voltage ratios into transparent decibel metrics.
%   The voltage-derived power calculation assumes real, positive resistance:
%   P = V_rms^2/R. Zero signal power or voltage is represented as -Inf dB.
arguments
    powerW (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = 2e-3
    voltageRms (1,1) double {mustBeReal,mustBeFinite,mustBeNonnegative} = sqrt(2e-3*50)
    resistanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 50
    referencePowerW (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 1e-3
    referenceVoltageRms (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = sqrt(1e-3*50)
    referenceResistanceOhm (1,1) double {mustBeReal,mustBeFinite,mustBePositive} = 50
end

powerRatio = powerW/referencePowerW;
voltageRatio = voltageRms/referenceVoltageRms;

powerDb = 10*log10(powerRatio);
voltageDb = 20*log10(voltageRatio);

powerFromVoltageW = voltageRms^2/resistanceOhm;
referencePowerFromVoltageW = referenceVoltageRms^2/referenceResistanceOhm;
voltagePowerRatio = powerFromVoltageW/referencePowerFromVoltageW;
voltagePowerDb = 10*log10(voltagePowerRatio);
impedanceCorrectionDb = 10*log10(referenceResistanceOhm/resistanceOhm);

powerDbm = 10*log10(powerW/1e-3);
powerDbw = 10*log10(powerW/1);
voltageDbv = 20*log10(voltageRms/1);

out = struct( ...
    'powerW',powerW, ...
    'voltageRms',voltageRms, ...
    'resistanceOhm',resistanceOhm, ...
    'referencePowerW',referencePowerW, ...
    'referenceVoltageRms',referenceVoltageRms, ...
    'referenceResistanceOhm',referenceResistanceOhm, ...
    'powerRatio',powerRatio, ...
    'voltageRatio',voltageRatio, ...
    'powerDb',powerDb, ...
    'voltageDb',voltageDb, ...
    'powerFromVoltageW',powerFromVoltageW, ...
    'referencePowerFromVoltageW',referencePowerFromVoltageW, ...
    'voltagePowerRatio',voltagePowerRatio, ...
    'voltagePowerDb',voltagePowerDb, ...
    'impedanceCorrectionDb',impedanceCorrectionDb, ...
    'sameImpedanceAssumptionErrorDb',voltageDb-voltagePowerDb, ...
    'consistencyErrorDb',powerDb-voltagePowerDb, ...
    'powerDbm',powerDbm, ...
    'powerDbw',powerDbw, ...
    'voltageDbv',voltageDbv);
end
